config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/about'
  get 'pages/contact'
  resources :stocks
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:index, :show] do
    resources :portfolios do
      resources :positions
      resources :transactions
    end
  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :portfolio
end

app/controllers/positions_controller.rb
require_relative '..//helpers/positions_helper'

class PositionsController < ApplicationController
  before_action :authenticate_user!
  include PositionsHelper
  before_action :set_position, only: %i[show edit update destroy]

  # GET /positions or /positions.json
  def index
    @portfolio = Portfolio.find(params[:portfolio_id])
    @positions = Position.where(portfolio_id: params[:portfolio_id]).order(:created_at).reverse
  end

  # GET /positions/1 or /positions/1.json
  def show
    @portfolio = Portfolio.find(params[:portfolio_id])
  end

  # GET /positions/new
  def new
    @position = Position.new
    @portfolio = Portfolio.find(params[:portfolio_id])
  end

  # POST /positions or /positions.json
  def create
    @position = Position.new(position_params)
    @finnhub_client = FinnhubRuby::DefaultApi.new
    @stocks = Stock.where(portfolio_id: params[:portfolio_id])
    @stock_symbols = @stocks.all.map(&:ticker)

    respond_to do |format|
      if @position.save
        format.html { redirect_to user_portfolio_positions_path, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1 or /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to user_portfolio_position_url, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1 or /positions/1.json
  def destroy
    @position.destroy

    respond_to do |format|
      format.html { redirect_to user_portfolio_positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_position
    @position = Position.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def position_params
    params.require(:position).permit(:open_date, :symbol, :quantity, :cost_per_share, :commission_and_fee,
                                    :realized_profit_loss, :income, :portfolio_id, :reinvested_income)
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: @position, url: "/portfolios/#{params[:portfolio_id]}/positions/", class: "contents") do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cost_per_share %>
    <%= form.number_field :cost_per_share, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :portfolio_id, value: @portfolio.id %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/positions/_new.html.erb
<%= form_with(model: @position, url: "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/positions/", class: "contents") do |form| %>
  <% if position.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>
      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :open_date %>
    <%= form.date_field :open_date, value: Date.today, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, step: 0.01, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cost_per_share %>
    <%= form.number_field :cost_per_share, step: 0.01, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :commission_and_fee %>
    <%= form.number_field :commission_and_fee, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :realized_profit_loss %>
    <%= form.number_field :realized_profit_loss, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :portfolio_id, value: @portfolio.id %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-1 px-3 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/positions/_position.html.erb
<div id="<%= dom_id position %>", class="container flex">
  <div class="my-5 mr-5">
    <span class="inline-block font-medium mb-1">Symbol:</span>
    <span class="font-bold"><%= position.symbol %></span>
  </div>

  <div class="my-5 mr-5">
    <span class="inline-block font-medium mb-1">Quantity:</span>
    <span class="font-bold"><%= sprintf('%.2f', position.quantity.to_f) %></span>
  </div>

  <div class="my-5 mr-5">
    <span class="inline-block font-medium mb-1">Cost per share:</span>
    <span class="font-bold"><%= number_to_currency(position.cost_per_share) %></span>
  </div>
</div>

<% if action_name != "show" %>
  <%= link_to "Show", "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/positions/#{position.id}", class: "rounded-lg py-1 px-3 bg-dollar-split_blue inline-block font-medium text-white" %>
  <%= link_to 'Edit', "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/positions/#{position.id}/edit", class: "rounded-lg py-1 ml-2 px-3 bg-dollar-triad_blue inline-block font-medium text-white" %>
  <hr class="mt-6">
<% end %>

app/views/positions/_update.html.erb
<%= form_with(model: @position, url: "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/positions/#{position.id}", class: "contents") do |form| %>
  <% if @position.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% @position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :open_date %>
    <%= form.date_field :open_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", required: true %>
  </div>

  <div class="my-5">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cost_per_share %>
    <%= form.number_field :cost_per_share, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :portfolio_id, value: @portfolio.id %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-1 px-3 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing position</h1>

  <%= render "update", position: @position %>

  <%= link_to "Show this position", "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/positions/#{params[:id]}", class: "ml-2 rounded-lg py-1 px-3 bg-cyan-300 inline-block font-medium" %>
  <%= link_to "Back to positions", user_portfolio_positions_path, class: "ml-2 rounded-lg py-1 px-3 bg-cyan-500 inline-block font-medium" %>
</div>

app/views/positions/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Positions</h1>
    <%= link_to 'New position', new_user_portfolio_position_path, class: "rounded-lg py-1 px-3 bg-dollar text-white block font-medium" %>
    <%= link_to "Portfolios", user_portfolios_path, class: "rounded-lg py-1 px-3 bg-dollar text-white block font-medium" %>
  </div>

  <div id="positions" class="min-w-full">
    <%= render @positions %>
  </div>
</div>

app/views/positions/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New position</h1>

  <%= render "new", position: @position %>

  <%= link_to 'Back to positions', user_portfolio_positions_path, class: "ml-2 rounded-lg py-1 px-3 bg-cyan-300 inline-block font-medium" %>
</div>

app/views/positions/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @position %>

    <%= link_to 'Edit this position', "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/positions/#{params[:id]}/edit", class: "mt-2 rounded-lg py-1 px-3 bg-dollar-split_blue inline-block font-medium text-white" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this position', "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/positions/#{params[:id]}", method: :delete, class: "mt-2 rounded-lg py-1 px-3 bg-dollar-triad_red font-medium text-white" %>
    </div>
    <%= link_to 'Back to positions', user_portfolio_positions_path, class: "ml-2 rounded-lg py-1 px-3 bg-dollar inline-block font-medium" %>
  </div>
</div>