config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/about'
  get 'pages/contact'
  resources :stocks
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:index, :show] do
    resources :portfolios do
      resources :positions
      resources :transactions
    end
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :portfolio
end

app/controllers/stocks_controller.rb
require 'date'
require 'time'

class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_stock, only: %i[show edit update destroy]

  # GET /stocks or /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
    @stock_symbols = Stock.all.map(&:ticker)
    @finnhub_client = FinnhubRuby::DefaultApi.new
    @transaction = Transaction.find_by(symbol: @stock.ticker)
    @position = Position.find_by(symbol: @stock.ticker)
    @position ? @stock_data = @finnhub_client.company_profile2({ symbol: @position.symbol }) :
                @stock_data = @finnhub_client.company_profile2({ symbol: @stock.ticker })
    @position ? @company_news = @finnhub_client.company_news(@position.symbol, Date.today - 14, Date.today) :
                @company_news = @finnhub_client.company_news(@stock.ticker, Date.today - 14, Date.today)
    @position ? @insider = @finnhub_client.insider_transactions(@position.symbol) :
                @insider = @finnhub_client.insider_transactions(@stock.ticker)
    @position ? @earnings = @finnhub_client.company_earnings(@position.symbol, { limit: 5}) :
                @earnings = @finnhub_client.company_earnings(@stock.ticker, { limit: 5})
  end

  def get_stock_id(ticker)
    @stock = Stock.find_by(ticker:)
    @stock.id
  end

  # GET /stocks/new
  def new
    @stock = Stock.new(income: 0)
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stock
    @stock = Stock.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def stock_params
    params.require(:stock).permit(:ticker, :transaction_id, :realized_profit_loss, :commission_and_fee, :shares_owned, :income,
                                  :portfolio_id, :reinvested_income)
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_eps_surprises.erb
<% @earnings.first(4).each do |item| %>
  <div class="my-5 mr-5 flex">
    <div class="flex-row">
      <div>
        <span class="inline-block">Period: </span>
        <span class="font-semibold"><%= item.period %></span>
      </div>
      <div>
        <span class="inline-block">Estimate: </span>
        <span class="font-semibold"><%= number_to_currency(item.estimate, precision: 4, strip_insignificant_zeros: true) %></span>
      </div>
      <div>
        <span class="inline-block">Actual: </span>
        <span class="font-semibold"><%= number_to_currency(item.actual, precision: 4, strip_insignificant_zeros: true) %></span>
      </div>
      <div>
        <span class="inline-block">Surprise: </span>
        <span class="font-semibold"><%= number_to_currency(item.surprise, precision: 4, strip_insignificant_zeros: true) %></span>
      </div>
      <div>
        <span class="inline-block">Surprise percentage: </span>
        <span class="font-semibold"><%= number_to_percentage(item.surprise_percent, precision: 2) %></span>
      </div>
    </div>
  </div>
<% end %>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, class: "contents") do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :transaction_id %>
    <%= form.number_field :transaction_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :realized_profit_loss %>
    <%= form.number_field :realized_profit_loss, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :commission_and_fee %>
    <%= form.number_field :commission_and_fee, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :shares_owned %>
    <%= form.number_field :shares_owned, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

    <%= form.hidden_field :portfolio_id, value: @portfolio.id %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/stocks/_stock.html.erb
<div id="<%= dom_id stock %>", class="container w-full">
  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Name:</span>
    <span class="font-bold"><%= @stock_data.name %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Ticker:</span>
    <span class="font-bold"><%= stock.ticker %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Reliazed P/L:</span>
    <% red_or_green = stock.realized_profit_loss > 0 ? 'text-green-600' : 'text-red-600' %>
    <span class="font-bold <%= red_or_green %>"><%= number_to_currency(stock.realized_profit_loss) %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Transactions cost :</span>
    <span class="font-bold text-red-600"><%= number_to_currency(-1 * stock.commission_and_fee) %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Income:</span>
    <% red_or_green = stock.income >= 0 ? 'text-green-600' : 'text-red-600' %>
    <span class="font-bold <%= red_or_green %>"><%= number_to_currency(stock.income.round(2)) %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">You have:</span>
    <span class="font-bold"><%= stock.shares_owned.round(3).to_fs(:delimited) %> shares</span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Exchange:</span>
    <span class="font-bold"><%= @stock_data.exchange %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Country:</span>
    <span class="font-bold"><%= @stock_data.country %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Currency:</span>
    <span class="font-bold"><%= @stock_data.currency %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">IPO date:</span>
    <span class="font-bold"><%= @stock_data.ipo %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block font-medium mb-1">Web URL:</span>
    <span class="font-bold text-dollar-split_blue hover:text-dollar-triad_blue curson-pointer"><%= link_to @stock_data.weburl, @stock_data.weburl, target: :'_blank', rel: :'noopener noreferrer' %></span>
  </div>

  <div class="mb-1 mr-4">
    <span class="inline-block w-32"><%= image_tag @stock_data.logo || "company_logo.svg", alt:"company logo" %></span>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this stock", stock, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this stock', edit_stock_path(stock), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/stocks/_stock_news.erb
<% if @company_news.length == 0 %>
  <p>No recent company news</p>
<% else %>
  <% @company_news.first(10).each do |news| %>
    <div class="my-5 mr-5 flex">
      <div class="w-44">
        <div class="block w-44"><%= image_tag news.image.empty? ? "news.png" : news.image, class:"rounded" %></div>
        <span class="inline-block font-medium mb-1">Source:</span>
        <span class="font-bold"><%= news.source %></span>
      </div>
      <div class="ml-4">
        <span class="font-semibold hover:text-dollar-triad_blue"><%= link_to news.headline, news.url, target: :'_blank', rel: :'noopener noreferrer' %></span><br>
        <span><%= DateTime.strptime(news.datetime.to_i.to_s,'%s').strftime("%d-%m-%y") %></span>
        <br>
        <p class="mt-2"><%= news.summary %></p>
        <span class="font-semibold hover:text-dollar-triad_blue text-sm"><%= link_to 'Read more', news.url, target: :'_blank', rel: :'noopener noreferrer' %></span>
      </div>
    </div>
  <% end %>
<% end %>

app/views/stocks/_stock_trades.erb
<% if @insider.data.length == 0 %>
  <p>No insider trades</p>
<% else %>
  <% @insider.data.first(10).each do |item| %>
    <div class="my-5 mr-5 flex">
      <div class="flex-row">
        <div>
          <span class="inline-block">Name: </span>
          <span class="font-semibold"><%= item.name %></span>
        </div>
        <div>
          <span class="inline-block">Shares: </span>
          <span class="font-semibold"><%= item.share.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %></span>
        </div>
        <div>
          <span class="inline-block">Change: </span>
          <span class="font-semibold"><%= item.change.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %></span>
        </div>
        <div>
          <span class="inline-block">Transaction date: </span>
          <span class="font-semibold"><%= item.transaction_date || '' %></span>
        </div>
        <div>
          <span class="inline-block">Transaction code: </span>
          <span class="font-semibold"><%= item.transaction_code || '' %></span>
        </div>
        <div>
          <span class="inline-block">Transaction price: </span>
          <span class="font-semibold"><%= number_to_currency(item.transaction_price, precision: 4, strip_insignificant_zeros: true) || '' %></span>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/stocks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing stock</h1>

  <%= render "form", stock: @stock %>

  <%= link_to "Show this stock", @stock, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to stocks", stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/stocks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Stocks</h1>
    <%= link_to 'New stock', new_stock_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="stocks" class="min-w-full">
    <%= render @stocks %>
  </div>
</div>

app/views/stocks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New stock</h1>

  <%= render "form", stock: @stock %>

  <%= link_to 'Back to stocks', stocks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/stocks/show.html.erb
<h1 class="text-4xl font-bold text-center my-16 mb-8">Company info</h1>
<div class="mx-auto md:w-full w-full flex">
  <div class="flex-col w-1/4">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <div>
      <h3 class="text-2xl font-semibold mb-4">Company Data</h3>
      <%= render @stock %>
    </div>
    <div class="mt-4">
      <h3 class="text-2xl font-semibold mb-4">Earnings surprises</h3>
      <%= render "eps_surprises" %>
    </div>
  </div>
  <div class="w-1/2">
    <h3 class="text-2xl font-semibold mb-4">Company news</h3>
    <%= render "stock_news" %>
  </div>
  <div class="w-1/4">
    <h3 class="text-2xl font-semibold mb-4">Insider Trading</h3>
    <%= render "stock_trades" %>
  </div>
</div>