config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/about'
  get 'pages/contact'
  resources :stocks
  devise_for :users, controllers: {
    # registrations: 'users/registrations',
    # sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users, only: [:index, :show] do
    resources :portfolios do
      resources :positions
      resources :transactions
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  include Pagy::Frontend

  def reset_instance_variable
    @total_fees = 0
    @income_spent = 0
    @total_commissions = 0
    @portfolio = Portfolio.find(params[:portfolio_id])
    @positions = Position.where(portfolio_id: params[:portfolio_id])
  end

  def initial_setup
    @transaction = Transaction.new(transaction_params)
    @portfolio = Portfolio.find(params[:portfolio_id])
    @positions = Position.where(portfolio_id: params[:portfolio_id])
    @finnhub_client = FinnhubRuby::DefaultApi.new
    @stocks = Stock.where(portfolio_id: params[:portfolio_id])
    @stock_symbols = @stocks.all.map(&:ticker)
    @stock = @stocks.find_by(ticker: @transaction.symbol) unless @transaction.symbol == 'Cash'
  end

  def transaction_amount(transaction)
    (transaction.tr_type == 'Reinvest Div.' || transaction.tr_type == 'Dividend') ? @stock.shares_owned * transaction.div_per_share : transaction.quantity * transaction.price
  end

  def add_cost(transaction)
    transaction.commission.nil? ? transaction.commission = 0 : transaction.commission
    transaction.fee.nil? ? transaction.fee = 0 : transaction.fee
    @add_cost = transaction.commission + transaction.fee
  end

  def enough_cash?(transaction)
    @cash_position = Position.where(portfolio_id: params[:portfolio_id], symbol: 'Cash').first
    if transaction.tr_type == 'Buy' || transaction.tr_type == 'Buy to cover' || transaction.tr_type == 'Cash Out' || transaction.tr_type == 'Misc. Exp.' || (transaction.tr_type == 'Dividend' && @stock.shares_owned < 0)
      @transaction_net_cost = transaction_amount(transaction) + add_cost(transaction)
    end
    @cash_position.quantity >= @transaction_net_cost.abs
  end

  def symbol_exist?(transaction) # in position table
    @position = @positions.where(portfolio_id: params[:portfolio_id], symbol: transaction.symbol).first
    @position != nil
  end

  def ticker_exist?(transaction) # in Finnhub stocks database
    @ticker = @finnhub_client.quote(transaction.symbol).d != nil
  end

  def enough_shares?(transaction)
    if symbol_exist?(transaction) # in position table
      @position = @positions.where(portfolio_id: params[:portfolio_id], symbol: transaction.symbol).first
      @position.quantity ? @position.quantity : 0
      @position.quantity.abs >= transaction.quantity.abs
    else
      false
    end
  end

  def closing_date_earlier_than_opening_date?(transaction)
    if transaction.tr_type == 'Sell' || transaction.tr_type == 'Reinvest Div.' || transaction.tr_type == 'Shares out'
      existing_stock_opened_date = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id, tr_type: 'Buy').order('trade_date ASC').first.trade_date || Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id, tr_type: 'Shares in').order('trade_date ASC').first.trade_date
    elsif transaction.tr_type == 'Buy to cover'
      existing_stock_opened_date = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id, tr_type: 'Sell short').order('trade_date ASC').first.trade_date
    elsif transaction.tr_type == 'Cash In' || transaction.tr_type == 'Interest Inc.'
      existing_stock_opened_date = @portfolio.opened_date
    elsif transaction.tr_type == 'Cash Out' || transaction.tr_type == 'Misc. Exp.'
      cash_in = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id, tr_type: 'Cash In').order('trade_date ASC').first ||
                Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id, tr_type: 'Interest Inc.').order('trade_date ASC').first
      cash_in == nil ? existing_stock_opened_date = @portfolio.opened_date : existing_stock_opened_date = cash_in.trade_date
    elsif transaction.tr_type == 'Stock Split' || transaction.tr_type == 'Dividend'
      existing_stock_opened_date = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id, tr_type: 'Buy').order('trade_date ASC').first.trade_date if long_position_exist?(transaction)
      existing_stock_opened_date = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id, tr_type: 'Sell short').order('trade_date ASC').first.trade_date if short_position_exist?(transaction)
    elsif transaction.tr_type == 'Symbol Change'
      existing_stock_opened_date = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id).order('trade_date ASC').first.trade_date if @stock_symbols.include?(transaction.symbol)
    end
    transaction.trade_date < existing_stock_opened_date
  end

  def long_position_exist?(transaction)
    @position = @positions.find_by(portfolio_id: params[:portfolio_id], symbol: transaction.symbol)
    @position == nil ? false : @position.quantity.positive? ? true : false
  end

  def short_position_exist?(transaction)
    @position = @positions.find_by(portfolio_id: params[:portfolio_id], symbol: transaction.symbol)
    @position == nil ? false : @position.quantity.negative? ? true : false
  end

  def date_valid?(transaction)
    transaction.trade_date >= @portfolio.opened_date
  end

  def adjust_stock_split(transaction)
    @historical_transactions = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id).order('trade_date ASC')
    @historical_transactions.each do |trans|
      if trans.trade_date < transaction.trade_date && trans.tr_type != 'Stock Split'
        trans.update(quantity: trans.quantity * transaction.new_shares.to_f / transaction.old_shares.to_f)
        trans.update(price: trans.price * transaction.old_shares.to_f / transaction.new_shares.to_f)
        trans.save
      end
    end
    # TODO: this should be moved to a split_stock method in create_update_stock switch case.
    @stock.shares_owned = @stock.shares_owned * transaction.new_shares.to_f / transaction.old_shares.to_f
    @stock.save
  end

  def transaction_save(transaction, format)
    if transaction.tr_type == 'Dividend'
      transaction.quantity *= @stock.shares_owned
      transaction.price = transaction.div_per_share
    end
    if transaction.tr_type == 'Reinvest Div.'
      transaction.price = transaction.closing_price
      transaction.quantity = (transaction.div_per_share * @stock.shares_owned / transaction.closing_price).round(3)
    end
    if transaction.tr_type == 'Stock Split'
      adjust_stock_split(transaction)
      transaction.quantity = @stock.shares_owned
    end
    if transaction.tr_type == 'Symbol Change'
      @historical_transactions = Transaction.where(symbol: transaction.symbol, portfolio_id: transaction.portfolio_id).order('trade_date ASC')
      @historical_transactions.each do |trans|
        trans.update(symbol: transaction.new_symbol)
        trans.save
      end
    end
    if transaction.save
      format.html do
        redirect_to "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/transactions/#{params[:id]}", 
                    notice: 'Transaction was successfully created.'
      end
      format.json { render :show, status: :created, location: transaction }
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: transaction.errors, status: :unprocessable_entity }
    end
  end

  def buy_stock(transaction)
    if @stock_symbols.include?(transaction.symbol)
      if enough_cash?(transaction)
        unless short_position_exist?(transaction)
          @stock.shares_owned += transaction.quantity
          @stock.commission_and_fee += add_cost(transaction)
          @stock.save
          @portfolio.transactions_cost += add_cost(transaction)
          @portfolio.save
        end
      end
    else
      new_stock = Stock.create(ticker: transaction.symbol, transaction_id: transaction.id, realized_profit_loss: 0, income: 0,
                              reinvested_income: 0, commission_and_fee: add_cost(transaction), shares_owned: transaction.quantity,
                              portfolio_id: @portfolio.id)
      new_stock.save
      @portfolio.transactions_cost += add_cost(transaction)
      @portfolio.save
    end
  end

  def sell_stock(transaction)
    unless short_position_exist?(transaction)
      if enough_shares?(transaction)
        unless closing_date_earlier_than_opening_date?(transaction)
          position = @positions.where(portfolio_id: params[:portfolio_id], symbol: transaction.symbol).first
          @stock.realized_profit_loss += transaction_amount(transaction) - add_cost(transaction) - (transaction.quantity * position.cost_per_share)
          @stock.shares_owned -= transaction.quantity
          @stock.commission_and_fee += add_cost(transaction)
          @stock.save
          @portfolio.realized_profit_loss += transaction_amount(transaction) - add_cost(transaction) - (transaction.quantity * position.cost_per_share)
          @portfolio.transactions_cost += add_cost(transaction)
          @portfolio.save
        end
      end
    end
  end

  def sell_short_stock(transaction)
    if @stock_symbols.include?(transaction.symbol)
      unless long_position_exist?(transaction)
        @stock.shares_owned -= transaction.quantity
        @stock.commission_and_fee += add_cost(transaction)
        @stock.save
        @portfolio.transactions_cost += add_cost(transaction)
        @portfolio.save
      end
    else
        new_stock = Stock.create(ticker: transaction.symbol, transaction_id: transaction.id, realized_profit_loss: 0, income: 0, 
          reinvested_income: 0, commission_and_fee: add_cost(transaction), shares_owned: -1 * transaction.quantity, portfolio_id: @portfolio.id)
        new_stock.save
        @portfolio.transactions_cost += add_cost(transaction)
        @portfolio.save
    end
  end

  def buy_to_cover_stock(transaction)
    unless long_position_exist?(transaction)
      if short_position_exist?(transaction)
        if enough_cash?(transaction)
          if enough_shares?(transaction)

app/views/transactions/_form.html.erb
<%= form_with(model: transaction,
  url: "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/transactions/",
  class: "contents", data: { controller: 'forms'}) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% field_style = "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <div class="my-5">
    <label for="transaction_tr_type"></label>
    <%= form.select :tr_type, [["Transaction type", ''],
      ['Buy', 'Buy'],
      ['Sell', 'Sell'],
      ['Sell short', 'Sell short'],
      ['Buy to cover', 'Buy to cover'],
      ['Cash In', 'Cash In'],
      ['Cash Out', 'Cash Out'],
      ['Interest Inc.', 'Interest Inc.'],
      ['Misc. Exp.', 'Misc. Exp.'],
      ['Dividend ***', 'Dividend'],
      ['Reinvest Div. ***', 'Reinvest Div.'],
      ['Stock Split ***', 'Stock Split'],
      ['Symbol Change ***', 'Symbol Change'],
      ['Shares in **', 'Shares in'],
      ['Shares out', 'Shares out']],
      class:"#{field_style} text-red-800", required: true %>
      <sup class="block-inline text-red-600 text-lg ml-1"> **, ***</sup>
  </div>

  <div class="my-5">
    <%= form.date_field :trade_date, value: Date.today,
      class: "#{field_style}",
      required: true, placeholder:"Trade date" %>
  </div>

  <div class="my-5">
    <%= form.text_field :symbol, class: "#{field_style}", required: true, placeholder:"Symbol" %>
  </div>

  <div class="my-5">
    <%= form.text_field :new_symbol, class: "#{field_style} hidden", placeholder:"New Symbol" %>
  </div>

  <div class="my-5">
    <%= form.number_field :quantity, min: 0.001, step: 0.001, class: "#{field_style}", required: true, placeholder:"Quantity" %>
  </div>

  <div class="my-5">
    <%= form.number_field :new_shares, class: "#{field_style} hidden", placeholder:"New shares ratio" %>
  </div>

  <div class="my-5">
    <%= form.number_field :old_shares, class: "#{field_style} hidden", placeholder:"Old shares ratio" %>
  </div>

  <div class="my-5" id="price-div">
    <%= form.number_field :price, min: 0.000001, step: 0.000001, class: "#{field_style}", required: true, placeholder:"Price" %>
  </div>

  <div class="my-5">
    <%= form.number_field :div_per_share, min: 0.000001, step: 0.000001, class: "#{field_style} hidden", placeholder:"Dividend per share" %>
  </div>

  <div class="my-5">
    <%= form.number_field :closing_price, min: 0.01, step: 0.01, class: "#{field_style} hidden", placeholder:"Closing price before dividend's day" %>
  </div>

  <div class="my-5">
    <%= form.number_field :commission, min: 0, step: 0.01, class: "#{field_style}", placeholder:"Commission" %>
  </div>

  <div class="my-5">
    <%= form.number_field :fee, min: 0, step: 0.01, class: "#{field_style}", placeholder:"Fee" %>
  </div>

  <%= form.hidden_field :portfolio_id, value: @portfolio.id %>

  <div class="mt-5">
    <div class="text-xs font-semibold text-red-600 leading-3">* All transactions have to be recorded chronologicaly.</div>
    <div class="text-xs font-semibold text-red-600 leading-3">** Enter 0 for 'Average price per share' if received as a gift or matching shares.</div>
    <div class="text-xs font-semibold text-red-600 leading-3">*** Must be entered in each portfolio, which holds the same stock separetely.</div>
  </div>

  <div class="flex justify-center">
    <%= form.submit class: "mt-8 rounded-lg py-1 px-3 bg-dollar-split_blue inline-block font-medium text-white hover:bg-dollar-triad_blue" %>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>" class="flex flex-col">
  <% cell = "border border-slate-300 px-3" %>
  <tr>
    <% transaction.commission == nil ? transaction.commission = 0 : transaction.commission %>
    <% transaction.fee == nil ? transaction.fee = 0 : transaction.fee %>
    <% added_cost = transaction.commission + transaction.fee %>
    <% transaction_amount = transaction.quantity * transaction.price %>
    <td class="<%= cell %>"><%= transaction.tr_type %></td>
    <td class="<%= cell %>"><%= transaction.trade_date %></td>
    <td class="<%= cell %>"><%= transaction.symbol %></td>
    <% if transaction.tr_type == 'Symbol Change' %> 
      <td class="<%= cell %>"><%= transaction.new_symbol %></td>
    <% else %>
      <td class="<%= cell %>"></td>
    <% end %>
    <% if transaction.tr_type == 'Symbol Change' %>
      <td class="<%= cell %>"></td>
    <% else %>  
      <td class="<%= cell %>"><%= transaction.tr_type == 'Sell short' ? (-1 * transaction.quantity).to_fs(:delimited) : transaction.quantity.to_fs(:delimited) %></td>
    <% end %>
    <% if transaction.tr_type == 'Stock Split' %>
      <td class="<%= cell %>"><%= (transaction.quantity * transaction.old_shares / transaction.new_shares).to_fs(:delimited) %></td>
      <td class="<%= cell %>"><%= transaction.new_shares %> for <%= transaction.old_shares %></td>
    <% else %>
      <td class="<%= cell %>"></td>
      <td class="<%= cell %>"></td>
    <% end %>
    <% if transaction.tr_type == 'Symbol Change' %>
      <td class="<%= cell %>"></td>
    <% else %>
      <td class="<%= cell %>"><%= number_to_currency(transaction.price, precision: 5, strip_insignificant_zeros: true) if transaction.tr_type != 'Stock Split' %></td>
    <% end %>
    <td class="<%= cell %>"><%= number_to_currency(transaction.commission) %></td>
    <% @total_commissions += transaction.commission %>
    <td class="<%= cell %>"><%= number_to_currency(transaction.fee) %></td>
    <% @total_fees += transaction.fee %>
    <% if transaction.tr_type == 'Buy' || transaction.tr_type == 'Buy to cover' || transaction.tr_type == 'Cash Out' || transaction.tr_type == 'Misc. Exp.' %>
      <td class="<%= cell %> text-red-600"><%= number_to_currency(-1 * (transaction_amount + added_cost)) %></td>
      <% @income_spent -= transaction_amount + added_cost %>
    <% elsif transaction.tr_type == 'Sell' || transaction.tr_type == 'Sell short' || transaction.tr_type == 'Cash In' || transaction.tr_type == 'Interest Inc.' || transaction.tr_type == 'Dividend' || transaction.tr_type == 'Reinvest Div.' %>
      <% red_or_green = transaction_amount - added_cost >= 0 ? 'text-green-600' : 'text-red-600' %>
      <td class="<%= cell %> <%= red_or_green %>"><%= number_to_currency(transaction_amount - added_cost) %></td>
      <% @income_spent += transaction_amount - added_cost %>
    <% elsif transaction.tr_type ==  'Stock Split' || transaction.tr_type ==  'Symbol Change' %>
      <td class="<%= cell %>"></td>
    <% elsif transaction.tr_type == 'Shares in' %>
      <td class="<%= cell %> text-green-600"><%= number_to_currency(transaction_amount  + added_cost) %></td>
      <% @income_spent += transaction_amount - added_cost %>
    <% elsif transaction.tr_type == 'Shares out' %>
      <td class="<%= cell %> text-red-600"><%= number_to_currency(-1 * transaction_amount  + added_cost) %></td>
      <% @income_spent -= transaction_amount + added_cost %>
    <% end %>
    <% if action_name != "show" %>
      <td class="<%= cell %> py-1"><%= link_to "Show", "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/transactions/#{transaction.id}", class: "rounded-lg px-2 bg-dollar-split_blue block font-medium text-white hover:bg-dollar-triad_blue" %></td>
    <% end %>
  </tr>
</div>

app/views/transactions/_update.html.erb
<%= form_with(model: transaction, url: "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/transactions/#{transaction.id}", class: "contents") do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :tr_type %>
    <%= form.text_field :tr_type, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :trade_date %>
    <%= form.date_field :trade_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :commission %>
    <%= form.number_field :commission, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :fee %>
    <%= form.number_field :fee, step: 0.01, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :portfolio_id, value: @portfolio.id %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-1 px-5 bg-dollar-complement text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing transaction</h1>

  <%= render "update", transaction: @transaction %>

  <%= link_to "Show this transaction", "/users/#{current_user.id}/portfolios/#{params[:portfolio_id]}/transactions/#{params[:id]}", class: "ml-2 rounded-lg py-1 px-5 bg-dollar-split_blue inline-block font-medium text-white" %>
  <%= link_to "Back to transactions", user_portfolio_transactions_path, class: "ml-2 rounded-lg py-1 px-3 bg-dollar-triad_blue inline-block font-medium text-white" %>
</div>

app/views/transactions/index.html.erb
<div class="w-full">
  <% cell = "border border-slate-300 px-4" %>
  <h1 class="font-bold text-4xl mb-8">Transactions</h1>
  <div class="flex mb-4">
    <%= link_to 'New transaction', new_user_portfolio_transaction_path, class: "rounded-lg py-1 px-3 bg-dollar-split_blue text-white font-medium" %>
    <p class="ml-4 mt-1">Click on a column header (Type, Date, Symbol, Quantity or Price) to sort</p>
  </div>

  <%== pagy_nav(@pagy) %>

  <div id="transactions" class="min-w-full mt-6">
    <table class="table-auto mb-6 border-collapse border border-slate-400">
      <thead>
        <tr>
          <th class="<%= cell %>"><%= sort_link(@q, :tr_type, "Type") %></th>
          <th class="<%= cell %>"><%= sort_link(@q, :trade_date, "Date", default_order: :desc) %></th>
          <th class="<%= cell %>"><%= sort_link(@q, :symbol) %></th>
          <th class="<%= cell %>">New Symbol</th>
          <th class="<%= cell %>"><%= sort_link(@q, :quantity) %></th>
          <th class="<%= cell %>">Old Quantity</th>
          <th class="<%= cell %>">Split ratio</th>
          <th class="<%= cell %>"><%= sort_link(@q, :price) %></th>
          <th class="<%= cell %>">Commission</th>
          <th class="<%= cell %>">Fee</th>
          <th class="<%= cell %>">Total</th>
          <th colspan="2" class="<%= cell %>">Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render @transactions %>
      </tbody>
      <tfoot>
        <tr>
          <td class="<%= cell %> font-bold">Total</td>
          <% 7.times do %>
            <td class="<%= cell %>"></td>
          <% end %>
          <td class="<%= cell %> text-red-600">-<%= number_to_currency(@total_commissions) %></td>
          <td class="<%= cell %> text-red-600">-<%= number_to_currency(@total_fees) %></td>
          <% red_or_green = @income_spent > 0 ? 'text-green-600' : 'text-red-600' %>
          <td class="<%= cell %> <%= red_or_green %>"><%= number_to_currency(@income_spent) %></td>
          <td colspan="2"  class="<%= cell %>"></td>
        </tr>
      </tfoot>
    </table>
  </div>

  <%== pagy_nav(@pagy) %>

  <div class="mt-4">
    <%= link_to 'New transaction', new_user_portfolio_transaction_path, class: "rounded-lg py-1 px-3 bg-dollar-split_blue text-white font-medium" %>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="mx-auto md:w-1/4 w-full">
  <h1 class="font-bold text-2xl text-center mt-12 mb-8">New transaction<sup class="block-inline text-red-600"> *</sup></h1>
  <%= render "form", transaction: @transaction %>
  <%= link_to 'Back to transactions', user_portfolio_transactions_path, class: "w-fit mt-8 mx-auto rounded-lg py-1 px-3 bg-dollar-split_blue block font-medium text-white hover:bg-dollar-triad_blue" %>
</div>

app/views/transactions/show.html.erb
<h1 class="font-bold text-4xl mb-8">Transaction</h1>
<div class="mx-auto md:w-full w-full flex">
  <div class="">
    <table class="table-auto mb-6 border-collapse border border-slate-400">
      <thead>
        <tr>
          <th class="border border-slate-300 px-4">Type</th>
          <th class="border border-slate-300 px-4">Date</th>
          <th class="border border-slate-300 px-4">Symbol</th>
          <th class="border border-slate-300 px-4">New Symbol</th>
          <th class="border border-slate-300 px-4">Quantity</th>
          <th class="border border-slate-300 px-4">Old Quantity</th>
          <th class="border border-slate-300 px-4">Split ratio</th>
          <th class="border border-slate-300 px-4">Price</th>
          <th class="border border-slate-300 px-4">Commission</th>
          <th class="border border-slate-300 px-4">Fee</th>
          <th class="border border-slate-300 px-4">Total</th>
        </tr>
      </thead>
      <tbody>
        <%= render @transaction %>
      </tbody>
    </table>
    <%= link_to 'New transaction', new_user_portfolio_transaction_path, class: "rounded-lg py-1 px-3 bg-dollar-split_blue text-white font-medium" %>
    <%= link_to 'Back to transactions', user_portfolio_transactions_path, class: "rounded-lg py-1 px-3 bg-dollar-split_blue text-white inline-block font-medium hover:bg-dollar-triad_blue" %>
  </div>
</div>